### ISSUE TITLE
Abandon repository

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa-rest_-abandoned-#2]
The planned works are not cooperated by the committers. On the other hand, the original repository has merged the main repository repeatedly with commits added since then, making rebasing difficult. Perhaps we’d be better to rewrite from scratch.

For these reasons, abandoning this repository is suggested.

**Comment by racke** [comment]
I agree.

**Comment by ikedas** [comment]
The original repository [Renater/sympa](/Renater/sympa) appears to have been removed or made private. There has been no word from the committers.

This repository is abandoned.
